apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: avib-graph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neo4j
    statefulset.kubernetes.io/pod-name: avib-graph-neo4j-core-2
  name: avib-graph-neo4j-external-2
spec:
  loadBalancerIP: 20.97.27.89
  externalTrafficPolicy: Local
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: https
    port: 7473
    protocol: TCP
    targetPort: 7473
  selector:
    statefulset.kubernetes.io/pod-name: avib-graph-neo4j-core-2
  sessionAffinity: None
  type: LoadBalancer