# This ConfigMap gets passed to all core cluster members to configure them.
# Take note that some networking settings like internal hostname still get configured
# when the pod starts, but most non-networking specific configs can be tailored here.
#
# When your pods start, you will inherit the config in common-configmap.yaml, so you don't
# need to repeat any of that here, just focus on overrides that are different than what's there.
apiVersion: v1
kind: ConfigMap
metadata:
  name: "avib-graph-neo4j-externally-addressable-config"
data:
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_mode: CORE
  avib-graph_neo4j_core_0_NEO4J_dbms_default__advertised__address: 13.72.82.9
  avib-graph_neo4j_core_0_NEO4J_dbms_connector_bolt_advertised__address: 13.72.82.9:7687
  avib-graph_neo4j_core_0_NEO4J_dbms_connector_http_advertised__address: 13.72.82.9:7474
  avib-graph_neo4j_core_0_NEO4J_dbms_connector_https_advertised__address: 13.72.82.9:7473
  avib-graph_neo4j_core_1_NEO4J_dbms_default__advertised__address: 13.72.82.129
  avib-graph_neo4j_core_1_NEO4J_dbms_connector_bolt_advertised__address: 13.72.82.129:7687
  avib-graph_neo4j_core_1_NEO4J_dbms_connector_http_advertised__address: 13.72.82.129:7474
  avib-graph_neo4j_core_1_NEO4J_dbms_connector_https_advertised__address: 13.72.82.129:7473
  avib-graph_neo4j_core_2_NEO4J_dbms_default__advertised__address: 13.68.244.173
  avib-graph_neo4j_core_2_NEO4J_dbms_connector_bolt_advertised__address: 13.68.244.173:7687
  avib-graph_neo4j_core_2_NEO4J_dbms_connector_http_advertised__address: 13.68.244.173:7474
  avib-graph_neo4j_core_2_NEO4J_dbms_connector_https_advertised__address: 13.68.244.173:7473